"""
analysis/compile_findings.py
Reads CSV outputs from H1, H4, H2, H3 and generates HINDI_ANOMALY_FINDINGS.md.

Run after all hypothesis scripts have completed.
"""

import os
import csv

_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
_ROOT = os.path.dirname(_SCRIPT_DIR)

def read_csv(path):
    if not os.path.exists(path):
        return None
    with open(path, newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def fmt(val, decimals=4):
    try:
        return f"{float(val):.{decimals}f}"
    except (TypeError, ValueError):
        return str(val)


def main():
    h1 = read_csv(os.path.join(_SCRIPT_DIR, "fragmentation_ratio_by_language.csv"))
    h4 = read_csv(os.path.join(_SCRIPT_DIR, "dataset_distribution_by_language.csv"))
    h2 = read_csv(os.path.join(_SCRIPT_DIR, "transport_entropy_by_epoch_language.csv"))
    h3 = read_csv(os.path.join(_SCRIPT_DIR, "hindi_representation_drift.csv"))

    lines = []
    lines.append("# HINDI_ANOMALY_FINDINGS.md\n")
    lines.append("*Auto-generated by `analysis/compile_findings.py`. Do not edit manually.*\n")
    lines.append("\n---\n")

    # ── Context ─────────────────────────────────────────────────
    lines.append("## Context\n")
    lines.append(
        "XQuAD-hi F1 peaks at epoch 1 (67.09) then decays monotonically through epoch 4 (55.25), "
        "while SQuAD-EN F1 rises monotonically. This is a systematic phenomenon (low SD over 3 seeds). "
        "Four hypotheses were tested to identify the mechanism.\n"
    )

    # ── Summary table ────────────────────────────────────────────
    lines.append("## Hypothesis Summary\n")
    lines.append("| # | Hypothesis | Verdict | Evidence strength |\n")
    lines.append("|---|---|---|---|\n")

    # We'll fill in verdicts from data below; start with placeholders
    h1_verdict = "NOT RUN / DATA MISSING"
    h4_verdict = "NOT RUN / DATA MISSING"
    h2_verdict = "NOT RUN / DATA MISSING"
    h3_verdict = "NOT RUN / DATA MISSING"

    # ── H1 ───────────────────────────────────────────────────────
    lines.append("\n---\n\n## H1: Tokenization Fragmentation Ratio\n")
    if h1:
        lines.append("| Language | mean_ratio | median_ratio | std_ratio | n_samples | status |\n")
        lines.append("|---|---|---|---|---|---|\n")
        hi_row = None
        others = []
        for row in h1:
            lines.append(f"| {row['language']} | {fmt(row['mean_ratio'])} | {fmt(row['median_ratio'])} | "
                         f"{fmt(row['std_ratio'])} | {row['n_samples']} | {row['status']} |\n")
            if row["language"] == "HI" and row["status"] == "OK":
                hi_row = row
            elif row["status"] == "OK":
                others.append(row)
        if hi_row and others:
            hi_m = float(hi_row["mean_ratio"])
            best_other = max(float(r["mean_ratio"]) for r in others)
            pct = (hi_m - best_other) / max(best_other, 1e-9) * 100
            if pct > 20:
                h1_verdict = f"**SUPPORTED** — HI ratio {fmt(hi_m)} is {pct:.1f}% above next highest"
                lines.append(f"\n> **Verdict**: {h1_verdict}\n")
            else:
                h1_verdict = f"**NOT SUPPORTED** — HI ratio {fmt(hi_m)} only {pct:.1f}% above next highest (threshold >20%)"
                lines.append(f"\n> **Verdict**: {h1_verdict}\n")
        else:
            lines.append("\n> **Verdict**: INSUFFICIENT DATA (one or more languages missing)\n")
    else:
        lines.append("*Output file not found — H1 script may not have run.*\n")

    # ── H4 ───────────────────────────────────────────────────────
    lines.append("\n---\n\n## H4: Data-Distributional Check\n")
    if h4:
        cols = ["language", "n_total", "pct_unanswerable",
                "ans_len_words_mean", "ans_len_tokens_mean",
                "ctx_len_tokens_mean", "ans_pos_pct_mean",
                "ans_pos_head_pct", "ans_pos_mid_pct", "ans_pos_tail_pct", "status"]
        lines.append("| " + " | ".join(cols) + " |\n")
        lines.append("|" + "|".join(["---"] * len(cols)) + "|\n")
        notable_diffs = []
        hi_row = None
        others = []
        for row in h4:
            lines.append("| " + " | ".join(str(row.get(c, "N/A")) for c in cols) + " |\n")
            if row["language"] == "HI" and row["status"] == "OK":
                hi_row = row
            elif row.get("status") == "OK":
                others.append(row)
        # B3: Verdict uses TOKEN-based metrics only (ans_len_tokens_mean, ctx_len_tokens_mean).
        # ans_len_words_mean is shown in the table for reference but excluded from the verdict:
        # whitespace-split word counts reflect morphological segmentation heuristics that
        # differ per language (Hindi compound morphology vs Vietnamese monosyllabic structure)
        # rather than genuine answer complexity differences.
        for lang_row in others:
            for metric in ["ans_len_tokens_mean", "ctx_len_tokens_mean"]:
                try:
                    hi_v = float(hi_row[metric])
                    ot_v = float(lang_row[metric])
                    pct = abs(hi_v - ot_v) / max(ot_v, 1e-9) * 100
                    if pct > 25:
                        notable_diffs.append(f"{metric}: HI={hi_v:.2f} vs {lang_row['language']}={ot_v:.2f} ({pct:.1f}% diff)")
                except (TypeError, ValueError, KeyError):
                    pass
        if notable_diffs:
            h4_verdict = "**POSSIBLE SUPPORT** — notable token-based distributional differences (>25%)"
            lines.append(f"\n> **Verdict**: {h4_verdict}\n")
            lines.append("> (Primary metric: `ans_len_tokens_mean` and `ctx_len_tokens_mean`;\n")
            lines.append("> `ans_len_words_mean` shown for reference only — excluded from verdict)\n")
            lines.append(">\n> Notable differences:\n")
            for d in notable_diffs:
                lines.append(f"> - {d}\n")
        else:
            h4_verdict = "**NOT SUPPORTED** — token-based distributions broadly comparable"
            lines.append(f"\n> **Verdict**: {h4_verdict}\n")
            lines.append("> (Primary metric: `ans_len_tokens_mean` and `ctx_len_tokens_mean`;\n")
            lines.append("> `ans_len_words_mean` excluded from verdict — whitespace-split artifacts differ per language)\n")
    else:
        lines.append("*Output file not found — H4 script may not have run.*\n")

    # ── H2 ───────────────────────────────────────────────────────
    lines.append("\n---\n\n## H2: Transport Plan Entropy by Epoch\n")
    if h2:
        import statistics as _s
        lines.append("| Language | Epoch | Seed | mean_entropy | std_entropy | status |\n")
        lines.append("|---|---|---|---|---|---|\n")
        for row in h2:
            lines.append(f"| {row['language']} | {row['epoch']} | {row['seed']} | "
                         f"{fmt(row['mean_entropy'])} | {fmt(row['std_entropy'])} | {row['status']} |\n")

        ok_rows = [r for r in h2 if r["status"] == "OK"]
        hi_ep1 = [float(r["mean_entropy"]) for r in ok_rows if r["language"] == "HI" and str(r["epoch"]) == "1"]
        vi_ep1 = [float(r["mean_entropy"]) for r in ok_rows if r["language"] == "VI" and str(r["epoch"]) == "1"]
        hi_ep4 = [float(r["mean_entropy"]) for r in ok_rows if r["language"] == "HI" and str(r["epoch"]) == "4"]
        # For relative_growth, compare HI ep1→ep4 vs VI ep1→ep4 (same training span, 3 steps).
        # This isolates growth RATE independent of which checkpoint was selected for evaluation.
        vi_ep4 = [float(r["mean_entropy"]) for r in ok_rows if r["language"] == "VI" and str(r["epoch"]) == "4"]


        # B4: relative_growth table — shows offset at every epoch AND epoch-span growth rate
        if hi_ep1 and vi_ep1 and hi_ep4 and vi_ep4:
            hi_m1 = _s.mean(hi_ep1)
            vi_m1 = _s.mean(vi_ep1)
            hi_m4 = _s.mean(hi_ep4)
            vi_m4 = _s.mean(vi_ep4)
            hi_growth = (hi_m4 - hi_m1) / hi_m1 * 100
            vi_growth = (vi_m4 - vi_m1) / vi_m1 * 100
            lines.append("\n**Relative growth (ep1→ep4, same 3-step span for both languages):**\n")
            lines.append("| Language | entropy_ep1 (mean over seeds) | entropy_ep4 (mean over seeds) | relative_growth_ep1_to_ep4 |\n")
            lines.append("|---|---|---|---|\n")
            lines.append(f"| HI | {hi_m1:.4f} | {hi_m4:.4f} | {hi_growth:.1f}% |\n")
            lines.append(f"| VI | {vi_m1:.4f} | {vi_m4:.4f} | {vi_growth:.1f}% |\n")

        if hi_ep1 and vi_ep1:
            hi_m1 = _s.mean(hi_ep1)
            vi_m1 = _s.mean(vi_ep1)
            # B4: Two-part verdict: (a) offset at epoch 1 (supported), (b) growth rate (not supported)
            offset_supported = hi_m1 > vi_m1 * 1.05
            if offset_supported:
                h2_verdict = f"**SUPPORTED (offset)** — HI entropy at ep1={hi_m1:.4f} > VI={vi_m1:.4f}"
            else:
                h2_verdict = f"**NOT SUPPORTED (offset)** — HI entropy at ep1={hi_m1:.4f} vs VI={vi_m1:.4f} (comparable)"
            lines.append(f"\n> **Verdict**: {h2_verdict}\n")
            if hi_ep4 and vi_ep4:
                hi_m4 = _s.mean(hi_ep4)
                vi_m4 = _s.mean(vi_ep4)
                hi_growth = (hi_m4 - hi_m1) / hi_m1 * 100
                vi_growth = (vi_m4 - vi_m1) / vi_m1 * 100
                if hi_growth > vi_growth * 1.05:
                    # HI entropy grows faster (relative) → supports compounding hypothesis
                    growth_verdict = (f"**SUPPORTED (compounding)** — HI relative growth "
                                      f"{hi_growth:.1f}% > VI {vi_growth:.1f}% "
                                      f"(HI entropy increases faster in relative terms)")
                else:
                    # HI entropy grows slower or equally fast → offset is fixed, not compounding
                    growth_verdict = (f"**NOT SUPPORTED (faster growth)** — HI relative growth "
                                      f"{hi_growth:.1f}% vs VI {vi_growth:.1f}% (offset appears fixed, "
                                      f"not compounding; HI entropy grows {'slower' if hi_growth < vi_growth else 'similarly'} "
                                      f"than VI in relative terms)")
                lines.append(f"> **Verdict (growth rate)**: {growth_verdict}\n")
        else:
            lines.append("\n> **Verdict**: INSUFFICIENT DATA (missing OK runs at epoch 1)\n")

        if os.path.exists(os.path.join(_SCRIPT_DIR, "transport_entropy_chart.png")):
            lines.append("\n![Transport Entropy Chart](transport_entropy_chart.png)\n")
    else:
        lines.append("*Output file not found — H2 script may not have run.*\n")

    # ── H3 ───────────────────────────────────────────────────────
    lines.append("\n---\n\n## H3: Representation Drift\n")
    if h3:
        lines.append("| Language | Metric | Epoch A→B | mean_A | mean_B | Cohen's d | t_p | w_p |\n")
        lines.append("|---|---|---|---|---|---|---|---|\n")
        for row in h3:
            ep_range = f"{row.get('epoch_a','?')}→{row.get('epoch_b','?')}"
            lines.append(f"| {row['language']} | {row['metric']} | {ep_range} | "
                         f"{fmt(row['mean_a'])} | {fmt(row['mean_b'])} | {fmt(row['cohens_d'], 3)} | "
                         f"{fmt(row['t_p'], 4)} | {fmt(row['w_p'], 4)} |\n")

        # B2: Document the aggregation formula explicitly in the output.
        lines.append("\n> **Aggregation formula**: `total_effect_size = |d_dist_after| + |d_cos_after|`\n")
        lines.append("> (sum of absolute Cohen's d for the two primary drift metrics;\n")
        lines.append("> `norm_delta` and `common_mode` are reported for completeness but excluded\n")
        lines.append("> from the aggregate to avoid conflating magnitude-drift with direction-drift.)\n")

        # B1: Use symmetric span (HI 1→3 vs VI 1→3) as the primary verdict.
        # If HI 1→3 rows are absent (checkpoint not yet available), fall back to 1→4.
        hi_dist_13 = next((r for r in h3 if r["language"] == "HI" and r["metric"] == "dist_after"
                           and str(r.get("epoch_a")) == "1" and str(r.get("epoch_b")) == "3"), None)
        hi_cos_13  = next((r for r in h3 if r["language"] == "HI" and r["metric"] == "cos_after"
                           and str(r.get("epoch_a")) == "1" and str(r.get("epoch_b")) == "3"), None)
        hi_dist_14 = next((r for r in h3 if r["language"] == "HI" and r["metric"] == "dist_after"
                           and str(r.get("epoch_a")) == "1" and str(r.get("epoch_b")) == "4"), None)
        hi_cos_14  = next((r for r in h3 if r["language"] == "HI" and r["metric"] == "cos_after"
                           and str(r.get("epoch_a")) == "1" and str(r.get("epoch_b")) == "4"), None)
        vi_dist = next((r for r in h3 if r["language"] == "VI" and r["metric"] == "dist_after"), None)
        vi_cos  = next((r for r in h3 if r["language"] == "VI" and r["metric"] == "cos_after"), None)

        symmetric_available = bool(hi_dist_13 and hi_cos_13)
        hi_dist = hi_dist_13 if symmetric_available else hi_dist_14
        hi_cos  = hi_cos_13  if symmetric_available else hi_cos_14
        span_label = "1→3 (symmetric with VI)" if symmetric_available else "1→4 (⚠ asymmetric: HI epoch-3 ckpt missing)"

        if hi_dist and vi_dist and hi_cos and vi_cos:
            hi_eff = abs(float(hi_dist["cohens_d"])) + abs(float(hi_cos["cohens_d"]))
            vi_eff = abs(float(vi_dist["cohens_d"])) + abs(float(vi_cos["cohens_d"]))
            if hi_eff > vi_eff * 1.2:
                h3_verdict = f"**SUPPORTED** — HI total effect size |d|={hi_eff:.3f} > VI |d|={vi_eff:.3f} (span: {span_label})"
            else:
                h3_verdict = f"**NOT SUPPORTED** — HI |d|={hi_eff:.3f} not substantially > VI |d|={vi_eff:.3f} (span: {span_label})"
            lines.append(f"\n> **Verdict**: {h3_verdict}\n")
            if not symmetric_available and hi_dist_14:
                lines.append("> **⚠ Note**: HI 1→3 rows not yet in CSV (epoch-3 checkpoint not run).\n")
                lines.append("> Current verdict uses HI 1→4 — re-run `hindi_representation_drift.py`\n")
                lines.append("> to add the symmetric comparison and update the verdict.\n")
        else:
            lines.append("\n> **Verdict**: INSUFFICIENT DATA\n")
    else:
        lines.append("*Output file not found — H3 script may not have run.*\n")

    # ── Summary table (filled in) ────────────────────────────────
    summary_idx = next(i for i, l in enumerate(lines) if l.startswith("| # | Hypothesis"))
    summary_rows = [
        f"| H1 | Tokenization fragmentation (Devanagari subword ratio) | {h1_verdict} | See §H1 |\n",
        f"| H4 | Data-distributional differences (answer length/tokens, context length) | {h4_verdict} | See §H4 |\n",
        f"| H2 | Transport plan entropy (coherence of Sinkhorn γ) | {h2_verdict} | See §H2 |\n",
        f"| H3 | Representation drift (cosine alignment, norm change) | {h3_verdict} | See §H3 |\n",
    ]
    for j, row_line in enumerate(summary_rows):
        lines.insert(summary_idx + 2 + j, row_line)

    # ── Conclusion ───────────────────────────────────────────────
    lines.append("\n---\n\n## Conclusion\n")
    supported = [h for h, v in [("H1", h1_verdict), ("H2", h2_verdict),
                                 ("H3", h3_verdict), ("H4", h4_verdict)]
                 if "SUPPORTED" in v and "NOT" not in v]
    not_supported = [h for h, v in [("H1", h1_verdict), ("H2", h2_verdict),
                                     ("H3", h3_verdict), ("H4", h4_verdict)]
                     if "NOT SUPPORTED" in v]
    missing = [h for h, v in [("H1", h1_verdict), ("H2", h2_verdict),
                               ("H3", h3_verdict), ("H4", h4_verdict)]
               if "NOT RUN" in v or "INSUFFICIENT" in v]

    if supported:
        lines.append(f"**Hypotheses with supporting evidence**: {', '.join(supported)}\n\n")
    if not_supported:
        lines.append(f"**Hypotheses not supported by data**: {', '.join(not_supported)}\n\n")
    if missing:
        lines.append(f"**Hypotheses with missing/incomplete data**: {', '.join(missing)} "
                     f"— rerun corresponding scripts with correct checkpoint paths.\n\n")

    lines.append(
        "> **Negative results are reported as-is.** "
        "If all four hypotheses are not supported, the finding is that the Hindi degradation "
        "mechanism cannot be attributed to tokenization, data distribution, OT plan quality, "
        "or representation drift measured at the current granularity — and further analysis "
        "(e.g., gradient-level probing, layer-wise entropy, language-specific LoRA saturation) "
        "would be required before any causal claim can be made.\n"
    )

    # ── write ────────────────────────────────────────────────────
    out_path = os.path.join(_ROOT, "HINDI_ANOMALY_FINDINGS_v3.md")
    with open(out_path, "w", encoding="utf-8") as f:
        f.writelines(lines)
    print(f"\n[compile] Findings written to: {out_path}")


if __name__ == "__main__":
    main()
